#!/bin/bash
FLAG=0
FLAG2=0
while true; do
#BAT CHECK

BATCH=$(acpi -b | awk '{ split($5,a,":"); print substr($3,0,2), $4, "["a[1]":"a[2]"]" }' | awk '{print $1}')
BATST=$(acpi -b | awk '{ split($5,a,":"); print substr($3,0,2), $4, "["a[1]":"a[2]"]" }' | awk '{print $2}' | tr -d '%,')
if [ "$BATCH" = "Ch" ]
then
    FLAG=1
    FLAG2=1
elif [[ $BATST -le 5 ]] && [[ $FLAG == 1 ]]
then
    mplayer ~/dwm-camilo/sonidos/battery_low_low_2011.mp3 &
    notify-send -u critical "Batería baja." "Batería bajo el 5%" &
    FLAG=0
elif [[ $BATST -le 20 ]] && [[ $FLAG2 == 1 ]]
then
    mplayer ~/dwm-camilo/sonidos/battery_low_low_2011.mp3 &
    notify-send "Batería baja." "Batería bajo el 20%" &
    FLAG2=0
    fi
#CPU
read cpu a b c previdle rest < /proc/stat
prevtotal=$((a+b+c+previdle))
sleep 0.5
read cpu a b c idle rest < /proc/stat
total=$((a+b+c+idle))
cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
icon="🖥"
icon1=""
icon2=icon="⬇️"
icon3="⬆️"
icon4=""
icon5=""
SSID=$(nmcli -t -f active,ssid dev wifi | grep sí | cut -c 5- | cut -c -10)
#NET
 DEV=$(cat /proc/net/wireless | perl -ne '/(\w+):/ && print $1')
 R1=`cat /sys/class/net/$DEV/statistics/rx_bytes`
 T1=`cat /sys/class/net/$DEV/statistics/tx_bytes`
 sleep 1
 R2=`cat /sys/class/net/$DEV/statistics/rx_bytes`
 T2=`cat /sys/class/net/$DEV/statistics/tx_bytes`
 TBPS=`expr $T2 - $T1`
 RBPS=`expr $R2 - $R1`
 TKBPS=`expr $TBPS / 1024`
 RKBPS=`expr $RBPS / 1024`
 BAT=$(acpi -b | awk '{ split($5,a,":"); print substr($3,0,2), $4, "["a[1]":"a[2]"]" }' | tr -d ',' )
 VOL=$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')
 MEM=$(free -m | awk 'NR==2{printf "%s/%sMB\n", $3,$2,$3*100/$2 }')
 HDD=$(df -h | grep home | awk '{print $4 ,$5}')
 TIME=$(date +"%a, %B %d %l:%M%p"| sed 's/  / /g')
 MIC=$(amixer -D 'hw:0' | grep Capture | grep '\[' | grep Left | cut -c 43- | sed  -e 's/]//')
 if [ "$MIC" = "off" ]
 then
     MICICON=""
 else
     MICICON=""
     fi
#⬇️ $RKBPS kb ⬆️ $TKBPS kb
 MUTED=$(amixer sget Master | grep Left: | cut -d '[' -f 3 | sed -e 's/\]//')
 SSID=$(nmcli -t -f active,ssid dev wifi | grep sí | cut -d : -f 2)
 xsetroot -name " $cpu% | $icon1 $MEM |  $SSID | $icon4 $HDD |  $VOL $MUTED | $MICICON |  $BAT | $TIME"
done &
